### ISSUE TITLE
Repositório vazio

### ISSUE THREAD

**Issue by felipeleusin** [DeveloperCielo/Webservice-1.5-csharp#1]
Olá,

Cheguei aqui do site para desenvolvedores da Cielo. Este repositório será utilizado? Estão precisando de ajuda em alguma coisa?

**Comment by netojoaobatista** [comment]
Olá, @felipeleusin, sim, esse repositório será utilizado.

Houve um problema com o código C# e, por isso, ele foi temporariamente removido. Mas será disponibilizado novamente ainda essa semana.

**Comment by felipeleusin** [comment]
Ok! Obrigado!

**Comment by felipeleusin** [comment]
Olá, 

Tem alguma novidade com este repositório?
