### ISSUE TITLE
O tipo da propriedade ARP (autorização) esta incorreto

### ISSUE THREAD

**Issue by DanFerreira** [DeveloperCielo/Webservice-1.5-csharp#10]
O campo ARP das autorizações está tipado como int, porém a Cielo pode enviar valores contendo letras (T12345 por exemplo) o que, consequentemente, dará erro na deserialização.

( Ocorreu comigo em produção haha :| )

**Comment by netojoaobatista** [comment]
Tem razão, @DanFerreira. Você faz um PR, ou prefere que eu faça o ajuste por aqui?

**Comment by DanFerreira** [comment]
PR feito, @netojoaobatista 
Vlw

**Comment by netojoaobatista** [comment]
Obrigado pela contribuição, @DanFerreira! Sua PR já foi mesclada.

:smile:
