### ISSUE TITLE
Criação do Processo de novo numero de Token Gerado pela Cielo

### ISSUE THREAD

**Issue by ricardoruas88** [DeveloperCielo/Webservice-1.5-csharp#16]
Atividade relacionada ao item 3.2.3 Renova Fácil com Token
 Caso a transação recorrente tenha sido enviada através de um token, sua autorização será
negada e será retornado um novo token para ser utilizado.

Atividade já feita, porem irei deixar só no meu Fork, enquanto espero o outro PR para não dá problema.

**Comment by dorathoto** [comment]
Puxei para dar uma olhada e não compila.

TokenElement em  TransacaoElement.cs não é encontrado Linha 30.


Será que o certo seria?
     `public RetornoTokenElement.TokenElement token { get; set; }`

**Comment by ricardoruas88** [comment]
Estranho pq estou usando assim, deixa eu conferir se algo não foi.

**Comment by ricardoruas88** [comment]
Então, está certo, na verdade havia criado separado dentro da pasta Element, mantendo o padrão das outras classes e está rodando normal aqui.

**Comment by ricardoruas88** [comment]
Achei o erro ele não commitou o <Compile Include="Request\Element\TokenElement.cs" />
dentordo Cielo.csproj, mas já faço o Commit, mil perdões.

**Comment by dorathoto** [comment]
show..valeu..depois vou dar uma testada e vou ver se ajudo colocando um UnitTest junto pra facilitar os testes e ajudar os novas pessoas a desenvolver..
Você que subiu o cancelamento de transação por Tid ?

**Comment by ricardoruas88** [comment]
Opa foi sim, adicionei essa opções, pois na documentação, pois ele criava a transação, porém não tinha TID, só se vc tivesse gerado na hora. Na documentação você só precisa realmente do TID para cancelar, então criei essa outra opção de cancelamento.

**Comment by dorathoto** [comment]
show..funcionou 100% eu estava usando a máquina para fazer cancelamento...mas vou aproveitar então seu código.
