### ISSUE TITLE
Previsão?

### ISSUE THREAD

**Issue by bbeildeck** [DeveloperCielo/Webservice-1.5-csharp#2]
Boa tarde,

Há alguma previsão para a disponibilização do código da integração?
Caso ainda haja problemas, podemos ajudar. Obrigado!

**Comment by netojoaobatista** [comment]
Olá @bbeildeck.

Comentei com o @felipeleusin recentemente, na #1, que houve um problema com o código e por isso ele foi tirado do ar. Já estou finalizando os testes de integração com as correções do código. Não consegui publicá-lo ainda, mas acontecerá em breve.

**Comment by bbeildeck** [comment]
Olá @netojoaobatista 
Entendido, obrigado pela resposta rápida!
