### ISSUE TITLE
Problema com URL_Enconding do Token

### ISSUE THREAD

**Issue by ricardoruas88** [DeveloperCielo/Webservice-1.5-csharp#20]
Estava implementando e eles me informaram que eu tinha que passar o token nesse formato, se você faz um post na verdade eles teriam que tratar, mas vamos lá implementar.

**Comment by dorathoto** [comment]
Você diz em forçar o enconding pq o Token vem com caracteres especiais?

**Comment by dorathoto** [comment]
Se for isso, também daria para utilizar o `StringContent` ao invés do `FormUrlEncodedContent` não cheguei a implementar assim, pois a de cima funciona 100%

```
private async Task<string> sendHttpRequest(string mensagem)
{
    var data = new Dictionary<string, string>();
    data.Add("mensagem", mensagem);

    using (var cliente = new HttpClient())
    {
        var chaves = new string[data.Count];
        var itens = new string[data.Count];

        data.Keys.CopyTo(chaves, 0);
        for (var indice = 0; indice < itens.Length; indice++)
        {
            var chave = chaves[indice];
            itens[indice] = chave + '=' + data[chave];
        }

        var encoded = Uri.EscapeDataString(String.Join("&", itens)).Replace("%20", "+");
        using (var conteudo = new StringContent(encoded, Encoding.UTF8, "application/x-www-form-urlencoded"))
        {
            var response = await cliente.PostAsync("minha url", conteudo);
            return await response.Content.ReadAsAsync<string>();
        }
    }
}
```
chamando:
```
var mensagem = "Hello Wolrd";
var response = Task.Run<string>(async () => await sendHttpRequest(mensagem)).Result;
```

**Comment by ricardoruas88** [comment]
Na verdade no meu código só chamo para o token System.Web.HttpUtility.UrlEncode(transaction.token.code)

**Comment by dorathoto** [comment]
hj tive problema com isso, e nem com meu código nem com o código original @netojoaobatista  não funcionava.
resolvi depois de um bom tempo de debug 

`var holder = cielo.holder(Uri.EscapeDataString(TokenCliente.Token));`

**Comment by dorathoto** [comment]
acho que o correto era arrancar todo esse código atual e utilizar o RestSharp
