### ISSUE TITLE
Erro em operações de débito

### ISSUE THREAD

**Issue by vitoravale** [DeveloperCielo/Webservice-1.5-csharp#21]
Ao tentar realizar uma operação de débito, onde está sendo enviada a seguinte mensagem pela transação:

```xml
<?xml version="1.0"?>
<requisicao-transacao xmlns="http://ecommerce.cbmp.com.br" versao="1.3.0" id="64b9237a-2419-4b9a-9add-0d804fa7b0aa" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<dados-ec>
		<numero>1006993069</numero>
		<chave>25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3</chave>
	</dados-ec>
	<dados-portador>
		<numero>5453010000066167</numero>
		<validade>201805</validade>
		<nome-portador>TESTE</nome-portador>
	</dados-portador>
	<dados-pedido>
		<numero>2</numero>
		<valor>500</valor>
		<moeda>986</moeda>
		<data-hora>2016-04-29T12:20:26</data-hora>
		<descricao>Pedido 2</descricao>
		<idioma>PT</idioma>
		<taxa-embarque>0</taxa-embarque>
	</dados-pedido>
	<forma-pagamento>
		<bandeira>mastercard</bandeira>
		<produto>A</produto>
		<parcelas>1</parcelas>
	</forma-pagamento>
	<url-retorno>http://localhost:7000/conta/pedido/2</url-retorno>
	<autorizar>3</autorizar>
	<capturar>true</capturar>
</requisicao-transacao>
```

recebo como retorno o seguinte erro:

```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<erro xmlns="http://ecommerce.cbmp.com.br" id="64b9237a-2419-4b9a-9add-0d804fa7b0aa">
	<codigo>086</codigo>
	<mensagem>Obrigatório o envio dos campos CAVV e XID</mensagem>
</erro>
```

Na [documentação](https://developercielo.github.io/Webservice-1.5/) disponível não consegui identificar, além da descrição do erro presente na seção Códigos de Erros, o que seriam esses campos e como os mesmos devem ser enviados.

Seria isto algo de configuração da conta do cliente junto à cielo ou será necessário alguma adição à solução para passar estes campos?

Caso seja uma adição, sabem onde encontro a documentação sobre estes campos para que eu possa realizar?

**Comment by dorathoto** [comment]
como vc está chamando a cielo.transactionRequest? Lembre-se que vc deve enviar o holder
ex:
```
Holder holder = cielo.holder ("4012001038443335", "2018", "05", "123");
holder.name = "Fulano Portador da Silva";
```
Mesmo quando é um token (não lembro se recorrencia tem débito) também deve enviar o Holder com o CVV
OBS: Rezo que esse número que vc postou seja um cartão fake..rs

**Comment by vitoravale** [comment]
@dorathoto estou enviando a transação completa contendo:

- holder
- order
- paymentMethod
- returnURL
- authorize
- capture

algo próximo à:

```
var transaction = cielo.transactionRequest(holder, order, new PaymentMethod(PaymentMethod.VISA, PaymentMethod.DEBITO, 1), "http://localhost/cielo", Transaction.AuthorizationMethod.AUTHORIZE_IF_AUTHENTICATED, true);
```

Segundo a documentação esta requisição deverá retornar a `<url-autenticacao>` para que o usuário seja redirecionado e realize a confirmação junto ao emissor.

PS: Os dados do cartão são dos dados para teste da documentação

**Comment by dorathoto** [comment]
Você já debugou para ver se no seu holder está realmente o CVV ?

Bom eu nunca utilizei o `Transaction.AuthorizationMethod.AUTHORIZE_IF_AUTHENTICATED` então vou passar @netojoaobatista que conheçe 110% o código

Só utilizo AUTHORIZE,RECURRENCE,AUTHORIZE_WITHOUT_AUTHENTICATION

**Comment by vitoravale** [comment]
O código de segurança (CVV) não estava sendo enviado, ajustei na classe _TransactionRequest (Ln52)_ adicionando `codigoSeguranca = transaction.holder.cvv`. Depois irei enviar um PR disto.

Quanto ao `AuthorizationMethod` escrevi o errado, estou utilizando o `Transaction.AuthorizationMethod.AUTHORIZE_WITHOUT_AUTHENTICATION`

**Comment by dorathoto** [comment]
Você tem razão, o último commit do @ricardoruas88  quebrou o código removendo o CVV

Como era: (Funcionando)
```
				dadosPortador = new DadosPortadorElement {
					numero = transaction.holder.number,
					validade = transaction.holder.expiration,
					nomePortador = transaction.holder.name,
                    token = transaction.holder.token,
                    codigoSeguranca = transaction.holder.cvv
```

Como ficou(quebrado)
```
                dadosPortador = string.IsNullOrEmpty(transaction.holder.token) ?
                    new DadosPortadorElement {
                        numero = transaction.holder.number,
                        validade = transaction.holder.expiration,
                        nomePortador = transaction.holder.name
                    } 
                    : new DadosPortadorElement {
                        token = transaction.holder.token
                    },

```
@netojoaobatista @ricardoruas88  verificar o código

**Comment by ricardoruas88** [comment]
Realmente foi burrice minha, não percebi a remoção do CVV. Peço desculpas aos envolvidos.

**Comment by vitoravale** [comment]
Quanto ao código de segurança eu enviei um PR, continuo com problemas na questão do débito, esperar ver se o @netojoaobatista consegue esclarecer o processo para mim :smile:

**Comment by danferreira** [comment]
@vitoravale qual o seu problema na questão do débito? 

Pelo que vi no seu xml de envio, voce esta solicitando uma Autorização Direta:

`<autorizar>3</autorizar>`

Como informado na documentação, a autenticação é obrigatória para transações de débito e opcional para o crédito.
Você precisa fazer uma transação autenticada em caso de débito (0, 1 ou 2 dependendo do seu requisito).

**Comment by vitoravale** [comment]
vou tentar aqui com isto @danferreira obrigado
