### ISSUE TITLE
Mudança de Namespace e Classe - Colisão de nomes

### ISSUE THREAD

**Issue by dorathoto** [DeveloperCielo/Webservice-1.5-csharp#22]
Sei que essa pergunta já foi questionada, mas agora proponho de tomarmos uma decisão:
[https://github.com/DeveloperCielo/Webservice-1.5-csharp/pull/14]

**Mudar ou não mudar o Namespace ou Classe**

Para ajudar informo esse artigo de [Eric Lippert](https://blogs.msdn.microsoft.com/ericlippert/2010/03/09/do-not-name-a-class-the-same-as-its-namespace-part-one/)

Sugestão:
**Namespace**: `Cielo `// visto que é um app para cielo
**Classe**: `CieloWebService` //visto que é o serviço de WebService, existem outros serviços.

Sei que alguns já estão utilizando assim @ricardoruas88 , @dorathoto

Fico no aguardo de outras pessoas:
@netojoaobatista @jeanstreleski @mayararomao @Saracielo

**Comment by vitoravale** [comment]
Acredito que esta seja uma boa solução.
O impacto desta mudança será mínimo para a maioria dos projetos que já utiliza a biblioteca e permitirá maior clareza na utilização.

**Comment by netojoaobatista** [comment]
O que pode ser feito é mudar o namespace para `CieloEcommerce`; a classe principal também pode ser renomeada para `WS15` ou ser mantida como `Cielo`, já que ao renomear o namespace deixamos de criar a confusão por causa dos nomes iguais.

**Comment by vitoravale** [comment]
Acredito que renomear para CieloEcomerce seja uma boa opção, @netojoaobatista vou providenciar e você aceita o PR depois.

**Comment by netojoaobatista** [comment]
Combinado, @vitoravale!
