### ISSUE TITLE
É necessário ter algum certificado para consumir o Web Service ?

### ISSUE THREAD

**Issue by Mantovanigomes** [DeveloperCielo/Webservice-1.5-csharp#25]
Olá, gostaria de consumir o Web Service da Cielo no meu Sistema Desktop (C#), Gostaria de saber se é necessário ter alguma certificação para usa-ló, exemplo: certificação PCI ? ou outras restrições. 
Obrigado!

**Comment by dorathoto** [comment]
pode usar sim.
certificação pci compliance somente se você for fazer um gateway(utilizar para pagamento de diversos outros clientes), se for para uso próprio tranquilo.

**Comment by netojoaobatista** [comment]
O certificado PCI-DSS deve ser utilizado se você for armazenar os dados do cliente; se não for armazenar nenhum dado sensível, basta um certificado SSL para trafegar os dados entre a máquina do cliente e sua aplicação.
