### ISSUE TITLE
Problema com Arp nos retornos

### ISSUE THREAD

**Issue by ricardoruas88** [DeveloperCielo/Webservice-1.5-csharp#26]
Algumas transações estão ocorrendo problemas tanto para receber o retorno do cancelamento como de pagamento. Alguém sabe pra que serve, removi e o problema parou. @netojoaobatista #

**Comment by ricardoruas88** [comment]
O Arp tem que ser string, pois ele pode receber caracteres alfa numericos. Já faço o pullrequest aqui.

**Comment by dorathoto** [comment]
também tive problema conforme esse link

https://github.com/DeveloperCielo/Webservice-1.5-csharp/issues/7
recebi alguns caracteres alfa numericos

**Comment by netojoaobatista** [comment]
@dorathoto, esse problema foi resolvido num PR; acabei fechando a issue sem perguntar, mas o problema já foi resolvido aí?

**Comment by dorathoto** [comment]
sim, tudo resolvido pode fechar
