### ISSUE TITLE
Dll C# Cielo - ORDER

### ISSUE THREAD

**Issue by rodrigoupone** [DeveloperCielo/Webservice-1.5-csharp#27]
Bom dia estou já a alguns dias tendo uma dor de cabeça danada com essa dll para integração com o Webservice.

Acontece que pegando o código modelo disponibilizado junto com o projeto para C# tudo ocorre perfeitamente.

Mas quando eu edito o código para passar os meus parâmetros as transações param de ser autorizadas.

Basta somente eu alterar essa linha:

`var order = cielo.order(randomOrder.Next(1000, 10000).ToString(), 1000);`

Para desta forma abaixo colocando os meus valores, já da problema.

`var order = cielo.order(newCompra.ClientID.ToString(), Convert.ToInt32(vTotal)); `

Como não achei nenhuma documentação sobre os métodos fiquei sem saber o que fazer, preciso mesmo de ajuda já mandei uns 15 e-mails pra cielo para homologação mas nenhum tive sucesso.

Obrigado.

**Comment by lucsobral** [comment]
Qual o valor do pedido? Não sei se é o caso, mas o servidor de homologação da cielo só aceita pedidos com valor decimal "00".

Atenciosamente,

Lucas Sobral


Date: Thu, 12 May 2016 10:00:18 -0700

**Comment by rodrigoupone** [comment]
No meu caso eu estou mandando pedido no valor de R$ 1,00. 
Logo quando converto para inteiro estou enviando o valor 1.

Como eu deveria enviar no caso do valor de R$ 1,00.


Certo mas isso é só no ambiente de homologação, em produção eu posso mandar R$ 35,99 por exemplo?

**Comment by lucsobral** [comment]
Em produção pode mandar qualquer valor.

Faz um teste, ao invés de enviar o valor 1, coloca fixo 100.
Eu lembro que tive muitos problemas por causa disso quando estava em homologação.

**Comment by dorathoto** [comment]
Lembrando que se quer fazer pagamento no valor de R$ 1,00 deve enviar 100

Se quer fazer um pagamento de R$ 35,99 deve enviar 3599

 


var order = cielo.order(newCompra.ClientID.ToString(), Convert.ToInt32(vTotal * 100));

//multiplicando seu valor por 100



 

De: rodrigoupone [mailto:notifications@github.com] 
Enviada em: quinta-feira, 12 de maio de 2016 14:26
Para: DeveloperCielo/Webservice-1.5-csharp <Webservice-1.5-csharp@noreply.github.com>
Assunto: Re: [DeveloperCielo/Webservice-1.5-csharp] Dll C# Cielo - ORDER (#27)

 

No meu caso eu estou mandando pedido no valor de R$ 1,00. 
Logo quando converto para inteiro estou enviando o valor 1.

Como eu deveria enviar no caso do valor de R$ 1,00.

Certo mas isso é só no ambiente de homologação, em produção eu posso mandar R$ 35,99 por exemplo?

**Comment by rodrigoupone** [comment]
Fala sério, eu não achei isso da documentação em lugar nenhum.

Problema resolvido galera.

Obrigado.
