### ISSUE TITLE
GIT CSharp

### ISSUE THREAD

**Issue by Rcisidoro** [DeveloperCielo/Webservice-1.5-csharp#3]
Olá, assinamos com a Cielo, porém não estou localizando os templates para C# no uso dos serviços, como faço para baixar esse modelo ?

**Comment by netojoaobatista** [comment]
@Rcisidoro, o código C# será publicado sexta-feira, depois de amanhã.

**Comment by Rcisidoro** [comment]
Perfeito João , fico no aguardo. 

Grato.

**Comment by netojoaobatista** [comment]
Apenas retificando, @Rcisidoro, sexta-feira é amanhã.

:smile:

**Comment by neutonmelo** [comment]
Bom dia Neto, tudo bem?

Ainda vai ser disponibilizado a biblioteca para integração? 

Obrigado!

**Comment by cabralRodrigo** [comment]
@netojoaobatista Também estou interessado nessa implementação. Tem alguma previsão de quando será disponibilizada para nós ?
