### ISSUE TITLE
Codigo de Erro 57

### ISSUE THREAD

**Issue by rodrigoupone** [DeveloperCielo/Webservice-1.5-csharp#30]
Boa noite pessoal, o meu código estava funcionando perfeitamente no ambiente de homologação, porem ao efetuar a mudança para o ambiente de produção o WS está retornando o codigo 57,

Código de segurança ausente.

Estou tentando efetuar o pagamento:
Valor - R$ 1,00 
Bandeira - Visa
Operação - Crédito

Alguém já passou por tal situação?

**Comment by dorathoto** [comment]
57 é problema de restrição no cartão.

 

Olhar a listagem de erros LR para identificar corretamente.

 

 <https://developercielo.github.io/Webservice-1.5/#códigos-de-erros> https://developercielo.github.io/Webservice-1.5/#códigos-de-erros

 

 

De: rodrigoupone [mailto:notifications@github.com] 
Enviada em: terça-feira, 17 de maio de 2016 09:31
Para: DeveloperCielo/Webservice-1.5-csharp <Webservice-1.5-csharp@noreply.github.com>
Assunto: [DeveloperCielo/Webservice-1.5-csharp] Codigo de Erro 57 (#30)

 

Boa noite pessoal, o meu código estava funcionando perfeitamente no ambiente de homologação, porem ao efetuar a mudança para o ambiente de produção o WS está retornando o codigo 57,

Código de segurança ausente.

Estou tentando efetuar o pagamento:
Valor - R$ 1,00 
Bandeira - Visa
Operação - Crédito

Alguém já passou por tal situação?

**Comment by rodrigoupone** [comment]
Estranho que está sendo disparado uma exception bem na hora de criar a transaction.


`

                var cielo = new Cielo.Cielo(ConfigApp.mid, ConfigApp.key, ConfigApp.UrlCieloEcommerce);

                var holder = cielo.holder(txtNroCartao.Text.Trim(), txtVencimento.Text.Substring(3), txtVencimento.Text.Substring(0, 2), txtCodSec.Text.Trim());
                holder.name = txtNome.Text.Trim();


                var totalCielo = (int)(vTotal * 100);

                var order = cielo.order(newCompra.ClientID.ToString(), totalCielo);

                PaymentMethod paymentMethod;
                if (RadioButtonVisa.Checked)
                {
                    paymentMethod = cielo.paymentMethod(PaymentMethod.VISA, PaymentMethod.CREDITO_A_VISTA);
                }
                else
                {
                    paymentMethod = cielo.paymentMethod(PaymentMethod.MASTERCARD, PaymentMethod.CREDITO_A_VISTA);
                }

               

                var transaction = cielo.transactionRequest(
                    holder,
                    order,
                    paymentMethod,
                    "http://localhost/cielo",
                    Transaction.AuthorizationMethod.AUTHORIZE_WITHOUT_AUTHENTICATION,
                    false
                );
`

A exception é disparada na hora de chamar transactionRequest.

**Comment by lucsobral** [comment]
Eu tive um problema parecido e só acontecia em produção.
Minha conta na cielo é pessoa física e tentei utilizar o meu cartão para teste, por algum motivo não funciona o pagamento com cartão com o mesmo CPF do cadastrado na conta da cielo.
Quando testei com o cartão de outra pessoa, funcionou perfeitamente.

**Comment by rodrigoupone** [comment]
Certo no meu caso é diferente o cartão que estou usando é meu, e o cadastro da cielo é do cliente.

Me ajudem por favor.

**Comment by RubensBR** [comment]
Qual é a exception que ocorre?

**Comment by netojoaobatista** [comment]
Sempre que ocorre uma exceção do ponto de vista da integração, ocorre uma `Cielo.CieloException`.
