### ISSUE TITLE
Disponibilização da última versão do pacote via nuget

### ISSUE THREAD

**Issue by vitoravale** [DeveloperCielo/Webservice-1.5-csharp#32]
Tomei a liberdade de iniciar a distribuição do pacote atual pelo Nuget afim de facilitar a utilização do mesmo nos projetos de minha equipe, ele está disponível com o nome de [CieloOficial](https://www.nuget.org/packages/CieloOficial/), pois o id Cielo já encontrava-se em uso por outro pacote.

Conforme citei no [PR#31](https://github.com/DeveloperCielo/Webservice-1.5-csharp/pull/31), seria interessante que os principais responsáveis pelo projeto me informassem seu nome de usuário no NuGet para que eu possa colocá-los como proprietários do pacote, assim qualquer um de nós poderíamos subir novas versões mantendo sempre atualizado com a versão do repositório.

Fico no aguardo do posicionamento de vocês: @dorathoto @ricardoruas88 @netojoaobatista

**Comment by ricardoruas88** [comment]
Opa, legal Cara. Então fiquei devendo fazer PR aqui, vou fazer esse sábado das correções das atividades que eu abri. Eu uso o meu login da empresa no nuget, porém se ele aceitar email que não seja da microsoft prefiro que seja ricardoruas88@gmail.com, senão ricardoruas88@hotmail.com

**Comment by vitoravale** [comment]
@ricardoruas88 tu liberando as correções aqui eu puxo e coloco lá no pacote. 

Quanto a conta no NuGet você pode se cadastrar com o e-mail desejado aqui: https://www.nuget.org/users/account/LogOn?returnUrl=%2F

Depois só me informe o nome de usuário escolhido para eu adicionar nos proprietários do pacote.

**Comment by ricardoruas88** [comment]
O meu usuário é o ricardoruas88

**Comment by vitoravale** [comment]
@dorathoto adicionei o seu também, agora ta aguardando você confirmar lá no painel

**Comment by dorathoto** [comment]
@vitoravale  cara não consta nada no meu nuget, não mandou pra outra pessoa?..rs

conta: dorathoto   email: leonardod@outlook.com
