### ISSUE TITLE
Qual encoding das respostas?

### ISSUE THREAD

**Issue by m98proxy** [DeveloperCielo/Webservice-1.5-csharp#34]
Qual encoding das respostas, em UTF8 as mensagens de resposta tem chegado com caracteres fora desta codificação:

Ex.:
O status 'Em autenticacao' n�o permite captura.

**Comment by dorathoto** [comment]
ISO-8859-1

https://developercielo.github.io/Webservice-1.5

**Comment by netojoaobatista** [comment]
> ISO-8859-1

:+1: 

O @dorathoto está correto, @m98proxy; na solução 1.5, as mensagens são retornadas em ISO-8859-1.
