### ISSUE TITLE
Visual Studio cannot start debugging

### ISSUE THREAD

**Issue by thales2606** [DeveloperCielo/Webservice-1.5-csharp#35]
Visual Studio cannot start debugging because the debug target 'bin\debug\Cielo.dll'
alguém pode me ajudar?

**Comment by dorathoto** [comment]
como vc anexou o projeto Cielo? apenas a DLL? anexo o projeto? creio que vc está tentando debugar o cielo, mas a dll não está no local correto. Anexa o projeto e coloca a referencia...creio que irá funcionar

**Comment by netojoaobatista** [comment]
Já conseguiu resolver o problema, @thales2606?

**Comment by thales2606** [comment]
desculpa a demora consegui resolver... estava tentando debugar o cielo, mas consegui resolver mt Obrigado!
