### ISSUE TITLE
Renova Fácil

### ISSUE THREAD

**Issue by dorathoto** [DeveloperCielo/Webservice-1.5-csharp#38]
Alguém sabe como funciona o renova fácil na recorrência? nosso sistema já contempla essa funcionalidade? alguém já desenvolveu algo?

**Comment by netojoaobatista** [comment]
@dorathoto, veja: [Autorização Recorrente](https://developercielo.github.io/Webservice-1.5/#autorização-recorrente). Em específico, a seção logo abaixo falando do funcionamento do Renova Fácil.

**Comment by dorathoto** [comment]
Mas entendo então que o sistema está recebendo o novo token? não sei se é possível simular isso em ambiente de teste.

**Comment by netojoaobatista** [comment]
Eu **acho** que não é possível simular isso no ambiente de testes, mas vou confirmar e te repasso o feedback.

**Comment by netojoaobatista** [comment]
É, @dorathoto, acabei de receber a informação de que não é possível simular o Renova Fácil em Sandbox.

**Comment by netojoaobatista** [comment]
É uma boa sugestão, @dorathoto!

Vou repassar a ideia dos números de cartões para simulações específicas.

:smile:

**Comment by dorathoto** [comment]
![cartoes_cielo](https://cloud.githubusercontent.com/assets/5939581/18489676/e52cdf6e-79d4-11e6-90be-aad1b59e7169.PNG)
Cartões de teste para Cielo
