### ISSUE TITLE
Recorrência com débito

### ISSUE THREAD

**Issue by dorathoto** [DeveloperCielo/Webservice-1.5-csharp#39]
Estou tentando fazer um pagamento com recorrência na função débito:
`
Transaction.AuthorizationMethod.RECURRENCE`
e
`PaymentMethod.DEBITO;`
porém obtenho o erro

> O produto n�o � cr�dito � vista.

quando mudo para
`PaymentMethod.CREDITO_A_VISTA;`
Funciona perfeitamente.

Já tentei com:
```
ONLY_AUTHENTICATE = 0, //não faz nda.
AUTHORIZE_IF_AUTHENTICATED = 1, //gera uma url não retorna o authentication
AUTHORIZE = 2, //gera uma url não retorna o authentication
AUTHORIZE_WITHOUT_AUTHENTICATION = 3, //somente para cartão crédito
RECURRENCE = 4 //erro acima
```

Update: Olhando na documentação java, vi que deveria fazer a opção 2 ou 1, com essa url devo encaminhar o usuário para ele fazer a autenticação e depois ele é retornado pra minha aplicação, correto?

**Comment by netojoaobatista** [comment]
@dorathoto, recorrência é apenas com crédito: [Autorização Recorrente](https://developercielo.github.io/Webservice-1.5/#autorização-recorrente)
