### ISSUE TITLE
Operação por Débito

### ISSUE THREAD

**Issue by dinhoguitars** [DeveloperCielo/Webservice-1.5-csharp#41]
algum exemplo de operação por débito? estou fazendo da seguinte forma, mas nao estou conseguindo o retorno da operação. faço o redirect ele vai para a pagina da cielo e volta p minha pagina

   Cielo cielo = new Cielo(ConfigApp.mid, ConfigApp.key, ConfigApp.UrlCieloEcommerce);

            Holder holder = cielo.holder("4012001037141112", "2018", "05", "123");
            holder.name = "Fulano Portador da Silva";
            
            Random randomOrder = new Random();

            Order order = cielo.order(randomOrder.Next(1000, 10000).ToString(), 10000);
            PaymentMethod paymentMethod = cielo.paymentMethod(PaymentMethod.VISA, PaymentMethod.DEBITO);
                        
            try
            {                    
                Transaction transaction = cielo.transactionRequest(
                                              holder,
                                              order,
                                              paymentMethod,
                                              ConfigApp.UrlRetornoAPP,
                                              Transaction.AuthorizationMethod.ONLY_AUTHENTICATE,
                                              true
                                          );

                if (transaction.authorization != null && transaction.authorization.lr == "00")
                {
                    Console.Write("Transação autorizada com sucesso. TID=");
                    Console.WriteLine(transaction.tid);
                }
                else
                {
                    Response.Redirect(transaction.authenticationUrl);
                }
            }
            catch (CieloException ex)
            {
                Console.WriteLine("Opz..");
                Console.WriteLine(ex.Code);
                Console.WriteLine(ex.Message);
            }

**Comment by netojoaobatista** [comment]
Se ele está voltando para a página que você definiu como URL de Retorno, então está funcionando como esperado.

:smile:

**Comment by dinhoguitars** [comment]
blz eu verifiquei, mas como fico sabendo se o pagamento foi
confirmado/autorizado?

recebo as seguintes variaveis de retorno

 string tid = Request.Form["Tid"].ToString();
                string eci = Request.Form["Eci"].ToString();
                string eciraw = Request.Form["EciRaw"].ToString();
                string veres = Request.Form["Veres"].ToString();
                string pares = Request.Form["Pares"].ToString();
                string cavv = Request.Form["Cavv"].ToString();
                string amount = Request.Form["Amount"].ToString();

2016-10-07 10:37 GMT-03:00 João Batista Neto <notifications@github.com>:

**Comment by netojoaobatista** [comment]
Seguindo o fluxo conforme explicado no manual:

> Quando há autenticação, o fluxo de execução da autorização acaba sendo feito em duas etapas, conforme mostrado no diagrama abaixo:

![Fluxo autenticação](https://developercielo.github.io/Webservice-1.5/images/fluxo-autenticacao.png)

Quando seu cliente é redirecionado de volta para sua página, você faz uma consulta ao TID da transação para ver o status da autorização.

**Comment by dinhoguitars** [comment]
SHow de bola! vlw João!

Em 7 de outubro de 2016 10:48, João Batista Neto <notifications@github.com>
escreveu:
