### ISSUE TITLE
Retorno da transação

### ISSUE THREAD

**Issue by thales2606** [DeveloperCielo/Webservice-1.5-csharp#42]
Olá, estou com um problema no código, quando tento passar um valor de R$ 65,32, eu recebo um retorno 32 através do transaction.authorization.lr, codigo abaixo

`  String mid = "1006993069";
            String key = "25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3";

            Cielo.Cielo cielo = new Cielo.Cielo(mid, key, "https://qasecommerce.cielo.com.br/servicos/ecommwsec.do");

            Holder holder = cielo.holder("4012001038443335", "2018", "05", "123");
            holder.name = "Fulano Portador da Silva";

            Random randomOrder = new Random();

            Order order = cielo.order(randomOrder.Next(1000, 10000).ToString(), 6532);
            PaymentMethod paymentMethod = cielo.paymentMethod(PaymentMethod.VISA, PaymentMethod.CREDITO_A_VISTA);
            
            try
            {
                Transaction transaction = cielo.transactionRequest(
                                              holder,
                                              order,
                                              paymentMethod,
                                              "http://localhost:57684/cielo",
                                              Transaction.AuthorizationMethod.AUTHORIZE_WITHOUT_AUTHENTICATION,
                                              false
                                          );
                
                if (transaction.authorization != null && transaction.authorization.lr == "00")
                {
                    HttpContext.Current.Response.Write("<script>alert('Transação autorizada com sucesso. TID=')</script>");
                    HttpContext.Current.Response.Write("<script> alert('"+transaction.tid+ "')</script>");
                }               
            }
            catch (CieloException e)
            {
                HttpContext.Current.Response.Write("<script>alert('Transação não autorizada com sucesso. TID=')</script>");
                HttpContext.Current.Response.Write("<script> alert('" + e.Code + "')</script>");
                HttpContext.Current.Response.Write("<script> alert('" + e.Message + "')</script>");
            }`

**Comment by netojoaobatista** [comment]
Você precisa elaborar melhor sobre o que está acontecendo; não consegui compreender seu problema e, visualmente, seu código está okay.

**Comment by thales2606** [comment]
eu não consigo passar valores com com casas decimais, exemplo se eu passa 1000 funciona, mas se eu passa 6532 não funciona.

**Comment by netojoaobatista** [comment]
Essa informação está dentro de uma caixa vermelha no manual: https://developercielo.github.io/Webservice-1.5/#chave-de-testes

> O valor do pedido além de seguir o formato sem pontos ou vírgulas decimais, deve terminar em “00”, caso contrário, a autorização será sempre negada. Exemplo: R$ 15,00 deve ser formatado como “1500”

**Comment by thales2606** [comment]
Obrigado!
