### ISSUE TITLE
Verificando Debito

### ISSUE THREAD

**Issue by dinhoguitars** [DeveloperCielo/Webservice-1.5-csharp#43]
Estou fazendo uma operação de débito. recebo apos o redirect as variaveis

                string tid = Request.Form["Tid"].ToString();
                string eci = Request.Form["Eci"].ToString();
                string eciraw = Request.Form["EciRaw"].ToString();
                string veres = Request.Form["Veres"].ToString();
                string pares = Request.Form["Pares"].ToString();
                string cavv = Request.Form["Cavv"].ToString();
                string amount = Request.Form["Amount"].ToString();

como verifico se o pagamento foi autorizado?

**Comment by netojoaobatista** [comment]
Essa informação consta no manual; por favor, veja: https://developercielo.github.io/Webservice-1.5/

> Quando há autenticação, o fluxo de execução da autorização acaba sendo feito em duas etapas, conforme mostrado no diagrama abaixo:

![Fluxo autenticação](https://developercielo.github.io/Webservice-1.5/images/fluxo-autenticacao.png)

Quando seu cliente é redirecionado de volta para sua página, você faz uma consulta ao TID da transação para ver o status da autorização.
