### ISSUE TITLE
LR e ARP devem ser do tipo string, pois em alguns casos vem string no XML 

### ISSUE THREAD

**Issue by TonyHenrique** [DeveloperCielo/Webservice-1.5-csharp#46]
Observei o nosso sistema estava tendo algumas Exceptions, e durante o debug vimos que algumas respostas estão vindo **string** nos campos LR e ARP
Portanto quando acontecia estes casos, de vir string em algum destes campos, o sistema dava erro na biblioteca Cielo, que estava esperando indevidamente apenas tipo **int**.

Para resolver, tive que alterar:
```
Cielo.Authorization
Cielo.Request.Element.AutorizacaoElement
```

mudar:
`public int lr { get; set; }`

para:
`public string lr { get; set; }`

mudar:
`public int arp { get; set; }`

para:
`public string arp { get; set; }`

Exemplo de XML que estava vindo:

```
<autorizacao>
    <codigo>5</codigo>
    <mensagem>Autorizacao negada</mensagem>
    <data-hora>2016-12-10T11:11:47.597-02:00</data-hora>
    <valor>1500</valor>
    <lr>KA</lr>
    <arp>B00235</arp>
    <nsu>014015</nsu>
</autorizacao>
```

**Comment by netojoaobatista** [comment]
Está correto; LR e ARP devem ser strings. Faça um Pull Request com suas alterações que faço a mesclagem.

:smile:

**Comment by TonyHenrique** [comment]
Fiz o Pull Request mas está dando erro eu não tenho permissão 
![erro](https://cloud.githubusercontent.com/assets/6307623/21075629/b4ed1634-befd-11e6-8ef2-bfc0fa7950d8.png)

**Comment by netojoaobatista** [comment]
Push você realmente não vai conseguir por causa das permissões; faça um pull request que eu faço o merge.

:smile:

**Comment by TonyHenrique** [comment]
Eu cliquei em Pull request, conforme pode se ver na imagem:
![p](https://cloud.githubusercontent.com/assets/6307623/21075848/933d91d4-bf03-11e6-9cb9-407027f43437.png)

então aquele erro:
![erro](https://cloud.githubusercontent.com/assets/6307623/21075852/bc72eb9e-bf03-11e6-99ff-7fd0c6ac12cd.png)

**Comment by TonyHenrique** [comment]
Deve ser porque não estou listado como **Contributors**

**Comment by TonyHenrique** [comment]
Não estou conseguindo fazer o Pull request, 
nem publicar o Branch com as alterações para serem verificadas aí.
