### ISSUE TITLE
Erro C# VS

### ISSUE THREAD

**Issue by clebertorrent** [DeveloperCielo/Webservice-1.5-csharp#8]
![cielo](https://cloud.githubusercontent.com/assets/11744577/14289830/e7ec26ae-fb32-11e5-897b-b38d2f4f90a4.png)

Ao adicionar a referencia da DLL Cielo, e usar o código de transação de exemplo, não me deixa compilar

**Comment by DanFerreira** [comment]
@clebertorrent Provavelmente você já solucionou o problema mas vai aqui uma luz.

Antes de gerar a DLL altere o método acessor da classe Cielo para public. Ele está como internal na implementação do repositório, logo voce não consegue instanciar de a classe por outro assembly.
Alem disso voce vai precisar instanciar sua classe da seguinte forma:

`Cielo.Cielo cielo = new Cielo.Cielo(mid, key, Cielo.Cielo.TEST);`

Isso porque a classe tem o mesmo nome do namespace.

**Comment by clebertorrent** [comment]
Isso.. eu fiz isso mesmo.

Agora meu problema esta na funcao debito
Em 11/04/2016 17:17, "Daniel Ferreira" <notifications@github.com> escreveu:

**Comment by dorathoto** [comment]
DanFerreira já falou os 2 problemas, namespace igual a classe e internal para public.
Recomendo mudar o namespace. Apesar que isso pode ser um tiro no pé se aqui começar a ter updates no código.

**Comment by vitoravale** [comment]
Também estou tendo problemas na função débito, fica retornando o erro 86 "XID e CAVV não fornecidos", alguém sabe resolver?

**Comment by dorathoto** [comment]
@vitoravale  Abre um novo Issue, ao invés de interagir nesse, que alias já devia estar fechado.
