### ISSUE TITLE
Correção para gerar cancelamento só com TID e Token sem transação prévia

### ISSUE THREAD

**Issue by ricardoruas88** [DeveloperCielo/Webservice-1.5-csharp#9]
Encontrei esse problemas na criação da requisição de cancelamento, então já criei o processo sem a necessidade de uma transação somente pelo TID. O mesmo caso com o token.

**Comment by netojoaobatista** [comment]
@ricardoruas88, envie o PR com sua correção, que eu faço a mesclagem no repositório da Cielo.

**Comment by ricardoruas88** [comment]
Fiz o PullRequest, vou ainda fazer mais testes e acrescentar mais coisas, pra ajudar e vou criando Issues aqui.

**Comment by netojoaobatista** [comment]
Fantástico, @ricardoruas88.

:smile:
